AmigoSecreto/Controllers/SiteController.cs
using AmigoSecreto.Models;
using AmigoSecreto.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using FastConsole;
using System.Threading.Tasks;

namespace AmigoSecreto.Controllers
{
    public class SiteController : Controller
    {
        private readonly ILogger<SiteController> _logger;

        private readonly IAmigoSecretoService _service;

        public SiteController(ILogger<SiteController> logger, IAmigoSecretoService service)
        {
            _logger = logger;
            _service = service;
        }

        [Route("/")]
        public IActionResult Index(string model)
        {
            return View();
        }

        [Route("NewRoom")]
        public IActionResult NewRoom()
        {
            return View();
        }

        [Route("Created/{id}")]
        public async Task<IActionResult> CreatedRoom(string id)
        {
            BasicRoom room = await _service.GetBasicRoom(id);

            if (room == null)
            {
                return RedirectToAction("PageNotFound");
            }

            string roomUrl = Url.RouteUrl("room", new { id }, Request.Scheme);

            return View(new CreatedRoomViewModel(roomUrl, room.Title));
        }

        [Route("Room/{id}/{errorId:int?}", Name = "room")]
        public async Task<IActionResult> Room(string id, int? errorId = null)
        {
            BasicRoom room = await _service.GetBasicRoom(id);

            if (room == null)
            {
                return RedirectToAction("PageNotFound");
            }

            return View(new RoomViewModel(room, errorId));
        }

        [Route("SecretFriend/{roomId}/{personId:int}")]
        public async Task<IActionResult> SecretFriend(string roomId, int personId)
        {
            var secret = await _service.GetSecretFriend(roomId, personId);

            if (secret.Result == Sfr.AlreadyRevelead)
            {
                return RedirectToAction("Room", new { id = roomId, errorId = secret.Person.Id });
            }
            if (secret.Result == Sfr.NotFound)
            {
                return RedirectToAction("PageNotFound");
            }

            return View(secret);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Route("NotFound")]
        public IActionResult PageNotFound()
        {
            return View("Error", new ErrorViewModel());
        }
    }
}

AmigoSecreto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    @*<!-- Google Search Console -->*@
    <meta name="google-site-verification" content="QNCeeqDbe5VxibYmJOvIAO8FXtcTJcsoKEajEMzfjOs" />

    @*<!-- Google AdSense -->*@
    <script data-ad-client="ca-pub-2731223979687390" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

    <!-- Materialize -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>

</head>

<body>

    <header>
        <nav style="min-height: 80px">
            <div class="nav-wrapper">
                <a class="brand-logo center logo" asp-controller="Site" asp-action="Index" style="height: 100%"><img src="~/AmigoSecreto_Logo_Roxo.jpg" alt="Logo" style="max-height: 100%; width: auto" /></a>
            </div>
        </nav>
    </header>

    <main role="main">
        <div class="container">
            @RenderBody()
        </div>
    </main>

    <footer class="page-footer">
        <div class="footer-copyright">
            <div class="container">
                Copyright &copy; 2020 - Rafael Hoyos, Pedro Braiti
                <a class="grey-text text-lighten-4 right" asp-controller="Site" asp-action="Index">Amigo Secreto</a>
            </div>
        </div>
    </footer>

    <!-- Materialize -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    @RenderSection("Scripts", required: false)

</body>

</html>